-- Populate the time dimension: every hour of March 2026, generated by
-- recursion (not extracted from staging), plus derived attributes.

INSERT INTO warehouse.dim_tempo (din_instante, data, ano, mes, dia, hora, dia_semana, nome_dia)
WITH RECURSIVE calendario AS (
    SELECT '2026-03-01 00:00:00'::TIMESTAMP AS hora
    UNION ALL
    SELECT hora + INTERVAL '1 hour'
    FROM calendario
    WHERE hora < '2026-03-31 23:00:00'::TIMESTAMP
)
SELECT
    hora                          AS din_instante,
    hora::DATE                    AS data,
    EXTRACT(YEAR    FROM hora)    AS ano,
    EXTRACT(MONTH   FROM hora)    AS mes,
    EXTRACT(DAY     FROM hora)    AS dia,
    EXTRACT(HOUR    FROM hora)    AS hora,
    EXTRACT(DOW     FROM hora)    AS dia_semana,
    TO_CHAR(hora, 'Day')          AS nome_dia
FROM calendario;